xabber_web/urls.py
from django.conf.urls import url, include
from .views import RootView, XabberWebInfoView

app_name = 'xabber_web'

urlpatterns = [
    url(r'^info', XabberWebInfoView.as_view(), name='info'),
    url(r'^$', RootView.as_view(), name='root'),
]

xabber_web/models.py
from django.db import models


class XabberWebSettings(models.Model):
    key = models.TextField(unique=True)
    value = models.TextField()

xabber_web/forms.py
from django import forms
from .config import domains_to_list


class XabberWebConfigForm(forms.Form):

    BOOL_CHOICE = (
        ('true', 'true'),
        ('false', 'false')
    )
    COLORS = (('red', 'red'), ('pink', 'pink'), ('purple', 'purple'), ('deep-purple', 'deep-purple'),
              ('indigo', 'indigo'), ('blue', 'blue'), ('light-blue', 'light-blue'), ('cyan', 'cyan'),
              ('teal', 'teal'), ('green', 'green'), ('light-green', 'light-green'), ('lime', 'lime'),
              ('amber', 'amber'), ('orange', 'orange'), ('deep-orange', 'deep-orange'),
              ('brown', 'brown'), ('blue-grey', 'blue-grey'))

    LOG_LEVEL_CHOICE = (
        ('NONE', 'NONE'),
        ('ERROR', 'ERROR'),
        ('WARN', 'WARN'),
        ('INFO', 'INFO'),
        ('DEBUG', 'DEBUG')
    )

    CONNECTION_URL = forms.CharField(
        max_length=200,
        required=False,
        empty_value=None,
        label='Connection url',
        widget=forms.TextInput(attrs={
            'size': 40,
            'hint': 'WebSocket URL used for creating connections'
        })
    )
    DISABLE_LOOKUP_WS = forms.ChoiceField(
        required=False,
        label='Disable lookup web socket url',
        initial='true',
        choices=BOOL_CHOICE,
        widget=forms.Select(attrs={
            'hint': 'Disable lookup for domain using websocket known hosts'
        })
    )

    LOG_LEVEL = forms.ChoiceField(
        required=False,
        label='Log level',
        choices=LOG_LEVEL_CHOICE,
        widget=forms.Select(attrs={
            'hint': 'Strophe console log level'
        })
    )

    LOGIN_DOMAINS = forms.CharField(
        required=False,
        label='Login domains',
        widget=forms.Textarea(attrs={
            'rows': 3,
            'hint': 'Domains list used for account authentication'
        })
    )

    REGISTRATION_DOMAINS = forms.CharField(
        required=False,
        label='Registration domains',
        widget=forms.Textarea(attrs={
            'rows': 3,
            'hint': 'Domains list used for account registration'
        })
    )

    RECOMMENDED_DOMAIN = forms.CharField(
        required=False,
        empty_value=None,
        label='Recommended domain',
        widget=forms.TextInput(attrs={
            'size': 40,
            'hint': 'Domain recommended for account registration when authentication occurs on a server where not all '
                    'client functions are supported. '
        })
    )

    TURN_SERVERS_LIST = forms.CharField(
        max_length=100,
        required=False,
        empty_value=None,
        label='Turn servers list',
        widget=forms.Textarea(attrs={
            'rows': 3,
            'hint': 'Servers for Jingle Message connection'
        })
    )

    REGISTRATION_CUSTOM_DOMAIN = forms.ChoiceField(
        required=False,
        label='Registration on custom domain',
        choices=BOOL_CHOICE,
        widget=forms.Select(attrs={
            'hint': 'Decides whether registration on domains not listed in REGISTRATION_DOMAINS is possible'
        })
    )

    REGISTRATION_BUTTON = forms.ChoiceField(
        required=False,
        label='Show registration button',
        choices=BOOL_CHOICE,
        widget=forms.Select(attrs={
            'hint': 'Show/Hide registration button'
        })
    )

    LOGIN_CUSTOM_DOMAIN = forms.ChoiceField(
        required=False,
        label='Login to custom domains',
        choices=BOOL_CHOICE,
        widget=forms.Select(attrs={
            'hint': 'Decides whether authentication on domains not listed in LOGIN_DOMAINS is possible'
        })
    )

    MAIN_COLOR = forms.ChoiceField(
        required=False,
        label='Main color',
        choices=COLORS,
        widget=forms.Select(attrs={
            'hint': 'Main client color for elements'
        })
    )

    is_enabled = forms.BooleanField(
        required=False,
        label='Advanced settings',
        initial=False
    )

    def clean(self, *args, **kwargs):
        cleaned_data = domains_to_list(self.cleaned_data, is_form=True)
        del cleaned_data['is_enabled']
        return cleaned_data

xabber_web/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic import TemplateView
from server.models import RootPageSettings
from xmppserverui.mixins import PageContextMixin, ServerInstalledMixin
from django.conf import settings
from .config import WHITENOISE_ROOT
from .forms import XabberWebConfigForm
from .models import XabberWebSettings
from .config import domains_to_string, get_xabber_config, update_config, XABBER_WEB_VER


class RootView(ServerInstalledMixin, TemplateView):
    template_name = 'xabber_web/index.html'

    def get(self, request, *args, **kwargs):
        xabber_web_config = get_xabber_config()
        for key, value in xabber_web_config.items():
            if isinstance(value, str) and value not in ('true', 'false'):
                xabber_web_config[key] = "'{}'".format(value)

        context = {'config': xabber_web_config}
        if XABBER_WEB_VER:
            context['xabber_web_ver'] = XABBER_WEB_VER
        return self.render_to_response(context=context)


class XabberWebInfoView(PageContextMixin, TemplateView):
    template_name = 'xabber_web/info.html'

    def get(self, request, *args, **kwargs):
        current_root_page = str(RootPageSettings.objects.all().first())
        warning = None
        if current_root_page not in __package__:
            warning = 'Set "Xabber for Web" as the root page in the settings'
        current_config = domains_to_string(get_xabber_config())
        form = XabberWebConfigForm(initial=current_config)
        return self.render_to_response(context={'warning': warning, 'form': form})

    def post(self, request, *args, **kwargs):
        if request.POST.get('reset'):
            XabberWebSettings.objects.all().delete()
            return HttpResponseRedirect(reverse('xabber_web:info'))
        else:
            form = XabberWebConfigForm(request.POST)
            if form.is_valid():
                update_config(form.cleaned_data)
                return HttpResponseRedirect(reverse('xabber_web:info'))
            return self.render_to_response(context={'form': form})

xabber_web/templates/xabber_web/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Xabber Web</title>
    <meta charset="utf-8">
    <link rel="shortcut icon" type="image/png" href="{% static 'xmppserverui/img/favicon.png' %}"/>
    <link rel="manifest" href="{% static 'xabberweb/manifest.json' %}">
    <style type="text/css">
        body {
            background: url({% static 'xmppserverui/img/bg.png' %}) 100% 100% no-repeat;
            background-size: cover;
            background-color: #fbfbfb;
            color: #000;
            font-size: 16px;
            margin: 0;
            height: 100%;
        }
        body.login .login-panel-footer {
                display: block !important;
        }
        .login-container-wrap {
                display: flex;
                flex-direction: column;
                justify-content: center;
                align-items: center;
                height: 90%;
        }
        .login-panel-footer {
                display: none;
                width: 100%;
                padding-top: 24px;
        }
        .login-panel-footer .footer-text {
                font-size: 16px;
                line-height: 24px;
                text-align: center;
                width: 560px;
                color: #9E9E9E;
                margin: 0 auto;
        }
        body.on-login > div.login-container-wrap {
                display: none;
        }
        .login {
            height: 100vh;
            overflow-y: auto;
            position: relative;
            display: flex;
            flex-direction: column;
            align-items: center;
        }
        .login .login__device {
        display: flex;
        margin: 24px 0;
        text-decoration: none;
    }

    .login .login__device img {
        margin: 16px auto 10px;
    }

    .login .login__device-android,
    .login .login__device-ios {
        width: 176px;
        display: flex;
        flex-direction: column;
        align-items: center;
        margin: 0 32px;
        text-decoration: none;
    }

    .login .login__device-android span,
    .login .login__device-ios span {
        display: block;
        margin-top: 10px;
        color: #fff;
        font-size: 16px;
        line-height: 24px;
        text-decoration: none;
    }
    </style>
</head>



<body style="height: 100%; width: 100%;">
    <div id="xabber-container" style="height: 100%; width: 100%;">
        <div class="login">
             <div class="login-container-wrap">
                    <div class="login-container"></div>
             </div>
            <div class="login__device">
                <a target="_blank" href="https://www.xabber.com/rel/client/android/last/xabber.apk" class="login__device-android">
                    <img src="{% static 'xmppserverui/img/client_android.svg' %}" alt="Android">
                    <span>Xabber for Android</span>
                </a>
                <a target="_blank" href="https://testflight.apple.com/join/mSP4WiEV" class="login__device-ios">
                    <img src="{% static 'xmppserverui/img/client_iphone.svg' %}" alt="Android">
                    <span>Xabber for iOS</span>
                </a>
            </div>
        </div>
    </div>
<script>
        document.addEventListener('DOMContentLoaded', () => {
            let js = document.createElement('script'),
                js_vendors = document.createElement('script'),
                css = document.createElement('link');
            js.src='/static/xabberweb/dist/xabber.main.js';
            js.onload = () => {
                xabber.configure({
                    {% for key, value in config.items %}
                      {% if key == 'CONNECTION_URL' %}
                          {{ key }}: {% if value %} {{ value|safe }}
                                     {% else %} (window.location.protocol === 'https:' ? 'wss' : 'ws') + '://' + window.location.hostname  + (window.location.protocol === 'https:' ? ':5443/ws' : ':5280/ws')
                                     {% endif %},
                      {% elif value %}
                         {{ key }}: {{ value|safe }},
                       {% endif %}
                     {% endfor %}
                });
                xabber.start();
            };
            js_vendors.src='/static/xabberweb/dist/xabber.vendors.js';
            document.head.appendChild(js_vendors);
            css.href='/static/xabberweb/dist/main.css';
            css.rel='stylesheet';
            document.head.appendChild(css);
            js_vendors.onload = () => {
                document.head.appendChild(js);
            };
        });
    </script>
</body>
</html>

xabber_web/templates/xabber_web/info.html
{% extends 'base.html' %}
{% block title %}XabberWeb Settings{% endblock %}
{% block main_content %}

    <div class="row no-gutters">
        <div class="col-sm-12 page-content">

    <div class="col breadcrumbs">
            <ul class="list-group list-group-flush list-group-horizontal">
                <li class="list-group-item"><h1>Xabber web settings</h1></li>
            </ul>
    </div>
        <div class="row no-gutters">
            <div class="col tabs">
                {% if warning %}
                <div class="alert alert-warning" role="alert">
                    {{ warning }}
                </div>
                {% endif %}
            </div>
        </div>
            <div style="margin-top:30px">
                <form method="post">
                {% csrf_token %}
                {% with form.LOGIN_DOMAINS as field %}
                    {% include 'xabber_web/input_field_with_popover.html' %}
                {% endwith %}
                {% with form.REGISTRATION_DOMAINS as field %}
                    {% include 'xabber_web/input_field_with_popover.html' %}
                {% endwith %}
                {% with form.REGISTRATION_BUTTON as field %}
                    {% include 'xabber_web/input_field_with_popover.html' %}
                {% endwith %}
                <hr>
                {% with form.is_enabled as field %}
                        {% include 'xabber_web/input_field.html' %}
                {% endwith %}
                <div style="display:none" id="advanced-settings">
                {% with form.CONNECTION_URL as field %}
                    {% include 'xabber_web/input_field_with_popover.html' %}
                {% endwith %}
                {% with form.LOG_LEVEL as field %}
                    {% include 'xabber_web/input_field_with_popover.html' %}
                {% endwith %}
                {% with form.MAIN_COLOR as field %}
                    {% include 'xabber_web/input_field_with_popover.html' %}
                {% endwith %}
                {% with form.REGISTRATION_CUSTOM_DOMAIN as field %}
                    {% include 'xabber_web/input_field_with_popover.html' %}
                {% endwith %}
                {% with form.LOGIN_CUSTOM_DOMAIN as field %}
                    {% include 'xabber_web/input_field_with_popover.html' %}
                {% endwith %}
                {% with form.DISABLE_LOOKUP_WS as field %}
                    {% include 'xabber_web/input_field_with_popover.html' %}
                {% endwith %}
                {% with form.RECOMMENDED_DOMAIN as field %}
                    {% include 'xabber_web/input_field_with_popover.html' %}
                {% endwith %}
                {% with form.TURN_SERVERS_LIST as field %}
                    {% include 'xabber_web/input_field_with_popover.html' %}
                {% endwith %}
                 {% for error in form.non_field_errors %}
                        <div class="form-group row">
                            <div class="col-sm-12 non-field-error">
                                {{ error }}
                            </div>
                        </div>
                    {% endfor %}
                </div>
                    <div class="row form-group form-btn-block" style="margin-left:-8px">
                        <div class="col-sm-12">
                            <button type="submit" class="btn btn-primary">Save</button>
                            <button type="submit" class="btn btn-secondary" name="reset" value="true">Reset</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    {{ block.super }}
    <script>
        function set_advanced_settings() {
            var checked = $('#id_is_enabled').prop('checked');
            if (checked)
                $('#advanced-settings').show();
            else
                $('#advanced-settings').hide();
        }

        function updateAdvancedSettings() {
            var checked = $('#id_is_enabled').prop('checked');
            if (checked)
                $('#advanced-settings').show();
            else
                $('#advanced-settings').hide();
        }

        $(document).ready(function() {
            $('#id_is_enabled').bootstrapToggle({
                on: 'Hide',
                off: 'Show'
                    });
            updateAdvancedSettings();

            $('#id_is_enabled').change(function() {
                updateAdvancedSettings();
            })
        });
    </script>
    <script>
        $(function () {
            $('[data-toggle="popover"]').popover()
        })
    </script>
{% endblock %}

xabber_web/templates/xabber_web/input_field.html
{% if not field.is_hidden %}
<div class="row form-group {% if field.errors %}invalid{% endif %}">
    <label for="{{ field.id_for_label }}" class="col-sm-3 col-form-label">
        {{ field.label }}
    </label>
    <div class="col-sm-9">
        {{ field }}
        {% if field.help_text %}
            <small class="form-text text-muted">{{ field.help_text }}</small>
        {% endif %}
        <div class="invalid-feedback d-block">
            {% for field_error in field.errors %}{{ field_error }} {% endfor %}
        </div>
    </div>
</div>
{% endif %}

xabber_web/templates/xabber_web/input_field_with_popover.html
{% if not field.is_hidden %}
<div class="row form-group {% if field.errors %}invalid{% endif %}">
    <label for="{{ field.id_for_label }}" class="col-sm-3 col-form-label">
        {{ field.label }}
    </label>
    <div class="col-sm-7">
        {{ field }}
        {% if field.help_text %}
            <small class="form-text text-muted">{{ field.help_text }}</small>
        {% endif %}
        <div class="invalid-feedback d-block">
            {% for field_error in field.errors %}{{ field_error }} {% endfor %}
        </div>
    </div>
    {% if field.field.widget.attrs.hint %}
    <div class="col-sm-2">
        <a tabindex="0" class="form-field-popover" role="button" data-toggle="popover"
           data-placement="bottom" data-html="true" data-trigger="focus"
           data-content="{{ field.field.widget.attrs.hint }}">i
        </a>
    </div>
    {% endif %}
</div>
{% endif %}